### ISSUE TITLE
Node not rendering

### ISSUE THREAD

**Issue by fmcpherson** [andysylvester/drummer-outline-renderers#1]
I copied your script. Created a new OMPL file and executed the script. Executed again per your instructions and for some reason the first node/paragraph is not rendering. I think I may have moved the nodes around so not sure if that is the cause. Here is a link to my OPML source: http://drummer.scripting.com/frankm/testOutlineToHTML.opml 

At the moment i don't have time to study your script to see if I can figure out the cause. Just wanted to tile the issue here so not forgetten.

**Comment by andysylvester** [comment]
Frank, thanks for trying out the script and for the report! I will take a look and get back to you shortly.

**Comment by andysylvester** [comment]
Frank, your file helped me find an error in the script. Please get a fresh copy and see if that fixes it for you, and let me know. 

The HTML file generated is stored in the Public Files folder that you get when you do a "Download my files" command in Drummer.

**Comment by fmcpherson** [comment]
Fixed: http://drummer.scripting.com/frankm/test.html 

Found the file too, I was looking in the wrong zip file. :(

**Comment by andysylvester** [comment]
Issue has been corrected.
