### ISSUE TITLE
HTML Link rendering issue

### ISSUE THREAD

**Issue by fmcpherson** [andysylvester/drummer-outline-renderers#2]
HTML anchor links are not rendering as expected. I selected text in the outline, clicked the link button in Drummer, and entered the URL. I did this in two spots. See the rendered file here: http://drummer.scripting.com/frankm/myOutline.html

View source shows the link was rendered as follows: <a href=&quot;https://github.com/andysylvester/drummer-outline-renderers&quot;>To use</a> The browser status bar shows that &quot; appears replace by my Drummer url, http://drummer.scripting.com/frankm. 

Source OPML: http://drummer.scripting.com/frankm/testOutlineToHTML.opml

**Comment by andysylvester** [comment]
Frank, I am aware of the problem and mentioned it in the README file. I had to add some logic to check for double-quote marks in the headline text to keep an error from occurring when I concatenate the strings together as they are read from the OPML file (it substitutes &quot; for "). The downside is that affects URL links. If you have any suggestions, I would welcome them!

**Comment by fmcpherson** [comment]
In fase this helps, I found the script I used to run in Fargo that did the same (or similar thing) that you are doing in you script. It doesn't run as is, but I thought I would point it to you in case it gives you an idea. Back then we could only write to local storage. I would basically run it which opened the file in a new tab, view source, then copy and past in to Wordpress. Look at the Display As Paragraphs script in http://drummer.scripting.com/frankm/sharedSource.opml

**Comment by andysylvester** [comment]
Just made another update, get a fresh copy of the script, let me know how it goes.

**Comment by fmcpherson** [comment]
Looks like that fixed the issue. See: http://drummer.scripting.com/frankm/myOutline.html

**Comment by andysylvester** [comment]
Closing this issue - problem solved!
