### ISSUE TITLE
Enhancement idea: file name

### ISSUE THREAD

**Issue by fmcpherson** [andysylvester/drummer-outline-renderers#5]
The script currently hardcodes the file name. If one wants to render and host multiple HTML files like a "standard" web site the file names need to be unique. One can simply prompt for a file name, store that in a variable and use that as so:

const url = file.makeFilePublic (htmlFileOut);

A step beyond is to store the file name value as a  opmlHeader, perhaps htmlFileName, so that for future edits the script can change for the value and if not null use it.

**Comment by andysylvester** [comment]
I will do this as the first enhancement, will let you know when it is ready.

**Comment by andysylvester** [comment]
I have a test version of the script ready, twoLevelOutlineRendererE (see http://drummer.scripting.com/PDXProtestNews/PDXSharedScripts.opml). The script will read the OPML header htmlFileName from the currently selected tab to be rendered (needs to be a private OPML file right now) and create a rendered HTML file with that file name. I have not added the check to use a default name yet, but wanted to get this out there for you to take a look at.

**Comment by andysylvester** [comment]
I have completed updates to the script, now called twoLevelOutlineRendererF (see http://drummer.scripting.com/PDXProtestNews/PDXSharedScripts.opml). The script will read the OPML header htmlFileName from the currently selected tab to be rendered (private OPML file only) and create a rendered HTML file with that file name. If the file is a private file without that header element, the file will be rendered as test.html. If the outline is a public outline/instant outline, the file will be rendered as myOutline.html. Take a look and let me know what you think, especially with the default names for the HTML renderings.

**Comment by fmcpherson** [comment]
I found two instances of the script in the above shared OPML. I grabbed the "F" version and got the results below.

Found a typo

console.log ("isInstantOutine = ", isInstantOutine ); the value should be isInstantOutline

After I fixed the above typo, the script ran but then attempted to load: 

http://drummer.scripting.com/frankm/file%20name:%20opmlToHtml.html

**Comment by andysylvester** [comment]
@fmcpherson, I took a look at your source OPML file (http://drummer.scripting.com/frankm/testOutlineToHTML.opml), the htmlFileName attribute is set to "file name: opmlToHtml.html". You should edit the OPML headers to just have the file name.

I have also created a new version of the rendering script (rev G, twoLevelOutlineRendererG (see http://drummer.scripting.com/PDXProtestNews/PDXSharedScripts.opml), which is able to read the htmlFileName attribute for both private and public files. Give that a try and let me know how it goes. Thanks for testing this!

**Comment by fmcpherson** [comment]
That’s odd, I don’t know how the OPML header got messed up, but I removed the file name portion and that resolved that issue.

--
Frank McPherson
***@***.***
frankm.info

**Comment by andysylvester** [comment]
I have updated my shared scripts file and this repo, closing this issue.
